services:
  # TRANSCRIÇÃO (Whisper)
  whisper:
    build: ./whisper
    container_name: whisper
    ports:
      - "9000:9000"
    devices:
      - "/dev/dxg:/dev/dxg" # O padrão correto para Windows/WSL2
    environment:
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
    restart: no

  # INTELIGÊNCIA (Ollama)
  #ollama:
  #  image: ollama/ollama:latest
  #  container_name: ollama
  #  privileged: true
  #  volumes:
  #    - ollama_data:/root/.ollama
  #    - /usr/lib/wsl:/usr/lib/wsl # PASSO VITAL: Mapeia os drivers do Windows para o Docker
  #  devices:
  #    - "/dev/dxg:/dev/dxg"      # Único caminho que o Windows entende para GPU
  #  environment:
  #    - HSA_OVERRIDE_GFX_VERSION=10.3.0
  #    - LD_LIBRARY_PATH=/usr/lib/wsl/lib # VITAL: Aponta para os drivers mapeados
  #  restart: no

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui_data:/app/backend/data
    restart: no

  # VOZ (Piper)
  piper:
    image: rhasspy/piper-http
    container_name: piper
    restart: no
    ports:
      - "5000:5000"
    volumes:
      - ./piper:/quality
    command: ["-m", "/quality/pt_BR-faber-medium.onnx", "--data-dir", "/quality"]

  # MAESTRO (Bot)
  bot:
    build: ./bot
    container_name: telegram_bot
    extra_hosts:
      - "host.docker.internal:host-gateway" # Isso cria a ponte Docker -> Windows
    depends_on:
      - whisper
      - piper
    env_file:
      - .env
    restart: no

  # Você pode remover o serviço 'ollama' do seu docker-compose, 
  # já que ele vai rodar direto no Windows agora.

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: no
    ports:
      - "8080:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:rw
    cap_add:
      - NET_ADMIN

volumes:
  ollama_data:
  open-webui_data: